import type { Brand, Campaign, Merchant } from "./types"

// ---------------------------------------------------------------------------
// Sample dataset for the Analytics prototype.
//
// Everything below reflects data that already exists in the current Pulse
// Merchant product model (brand + merchant ID / terminal / acquirer
// configuration, and campaign configuration). These are prototype/sample
// records for demonstration purposes only — not real merchant accounts.
//
// No transaction, customer, or attribution data is modeled here. See
// future-data.ts for the clearly-separated conceptual future-state shapes
// used only to render locked/"coming soon" UI treatments.
// ---------------------------------------------------------------------------

export const MERCHANT: Merchant = {
  id: "merchant-chalhoub",
  name: "Chalhoub Group",
  region: "United Arab Emirates",
  currency: "AED",
  contactEmail: "dennis@chalhoub.com",
}

export const BRANDS: Brand[] = [
  {
    id: "faces",
    name: "Faces",
    slug: "faces",
    website: "www.faces.ae",
    logoInitials: "FA",
    logoColor: "#171717",
    addedOn: "2026-01-12",
    merchantIds: [
      {
        id: "mid-faces-1",
        merchantId: "MID-7743-2210",
        acquirer: "Stripe",
        channel: "both",
        terminals: [
          { id: "tid-faces-1", terminalId: "TID-00921", channel: "in_store", terminalName: "Yas Mall, Abu Dhabi" },
          { id: "tid-faces-2", terminalId: "TID-00922", channel: "online", terminalName: "faces.ae checkout" },
        ],
      },
      {
        id: "mid-faces-2",
        merchantId: "MID-7743-2288",
        acquirer: "Network International",
        channel: "in_store",
        terminals: [
          { id: "tid-faces-3", terminalId: "TID-00930", channel: "in_store", terminalName: "Dubai Mall" },
        ],
      },
    ],
  },
  {
    id: "tryano",
    name: "Tryano",
    slug: "tryano",
    website: "www.tryano.ae",
    logoInitials: "TR",
    logoColor: "#7A1E2B",
    addedOn: "2026-01-12",
    merchantIds: [
      {
        id: "mid-tryano-1",
        merchantId: "MID-5521-0043",
        acquirer: "Stripe",
        channel: "both",
        terminals: [
          { id: "tid-tryano-1", terminalId: "TID-11002", channel: "in_store", terminalName: "Mall of the Emirates" },
          { id: "tid-tryano-2", terminalId: "TID-11003", channel: "online", terminalName: "tryano.ae checkout" },
        ],
      },
    ],
  },
  {
    id: "tanagra",
    name: "Tanagra",
    slug: "tanagra",
    website: "www.tanagra.ae",
    logoInitials: "TA",
    logoColor: "#8A6D3B",
    addedOn: "2026-02-03",
    merchantIds: [
      {
        id: "mid-tanagra-1",
        merchantId: "MID-3390-7761",
        acquirer: "Magnati",
        channel: "both",
        terminals: [
          { id: "tid-tanagra-1", terminalId: "TID-20911", channel: "in_store", terminalName: "City Centre Deira" },
          { id: "tid-tanagra-2", terminalId: "TID-20912", channel: "online", terminalName: "tanagra.ae checkout" },
        ],
      },
    ],
  },
  {
    id: "level-shoes",
    name: "LEVEL Shoes",
    slug: "level-shoes",
    website: "www.levelshoes.ae",
    logoInitials: "LS",
    logoColor: "#171717",
    addedOn: "2026-02-03",
    merchantIds: [
      {
        id: "mid-level-1",
        merchantId: "MID-6640-1187",
        acquirer: "Checkout.com",
        channel: "both",
        terminals: [
          { id: "tid-level-1", terminalId: "TID-30221", channel: "in_store", terminalName: "Dubai Mall" },
          { id: "tid-level-2", terminalId: "TID-30222", channel: "online", terminalName: "levelshoes.ae checkout" },
        ],
      },
    ],
  },
  {
    id: "sephora",
    name: "Sephora",
    slug: "sephora",
    website: "www.sephora.ae",
    logoInitials: "SE",
    logoColor: "#0F0F0F",
    addedOn: "2026-02-18",
    merchantIds: [
      {
        id: "mid-sephora-1",
        merchantId: "MID-4471-9902",
        acquirer: "Stripe",
        channel: "both",
        terminals: [
          { id: "tid-sephora-1", terminalId: "TID-40551", channel: "in_store", terminalName: "Mall of the Emirates" },
          { id: "tid-sephora-2", terminalId: "TID-40552", channel: "in_store", terminalName: "Abu Dhabi Corniche" },
          { id: "tid-sephora-3", terminalId: "TID-40553", channel: "online", terminalName: "sephora.ae checkout" },
        ],
      },
    ],
  },
  {
    id: "mac-cosmetics",
    name: "MAC Cosmetics",
    slug: "mac-cosmetics",
    website: "www.maccosmetics.ae",
    logoInitials: "MC",
    logoColor: "#0F0F0F",
    addedOn: "2026-03-05",
    merchantIds: [
      {
        id: "mid-mac-1",
        merchantId: "MID-9013-4456",
        acquirer: "Network International",
        channel: "in_store",
        terminals: [
          { id: "tid-mac-1", terminalId: "TID-50110", channel: "in_store", terminalName: "Dubai Mall" },
        ],
      },
    ],
  },
  {
    id: "body-shop",
    name: "The Body Shop",
    slug: "the-body-shop",
    website: "www.thebodyshop.ae",
    logoInitials: "BS",
    logoColor: "#1E6B3D",
    addedOn: "2026-03-05",
    merchantIds: [
      {
        id: "mid-bodyshop-1",
        merchantId: "MID-2287-6631",
        acquirer: "Magnati",
        channel: "both",
        terminals: [
          { id: "tid-bodyshop-1", terminalId: "TID-60771", channel: "in_store", terminalName: "Sharjah City Centre" },
          { id: "tid-bodyshop-2", terminalId: "TID-60772", channel: "online", terminalName: "thebodyshop.ae checkout" },
        ],
      },
    ],
  },
  {
    id: "bath-body-works",
    name: "Bath & Body Works",
    slug: "bath-body-works",
    website: "www.bathandbodyworks.ae",
    logoInitials: "BB",
    logoColor: "#B23A6B",
    addedOn: "2026-03-19",
    merchantIds: [
      {
        id: "mid-bbw-1",
        merchantId: "MID-8802-1145",
        acquirer: "Stripe",
        channel: "both",
        terminals: [
          { id: "tid-bbw-1", terminalId: "TID-70441", channel: "in_store", terminalName: "City Centre Deira" },
          { id: "tid-bbw-2", terminalId: "TID-70442", channel: "online", terminalName: "bathandbodyworks.ae checkout" },
        ],
      },
    ],
  },
]

export const CAMPAIGNS: Campaign[] = [
  // Faces
  {
    id: "camp-faces-summer",
    brandId: "faces",
    name: "Summer Cashback",
    status: "active",
    budget: 50000,
    cashbackPercentage: 10,
    minimumSpend: 200,
    cashbackCap: 300,
    startDate: "2026-07-01",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "both",
    distributionBank: "ADCB",
    createdAt: "2026-06-05",
    activatedAt: "2026-07-01",
    completedAt: null,
  },
  {
    id: "camp-faces-fall",
    brandId: "faces",
    name: "Fall Harvest Collection",
    status: "completed",
    budget: 30000,
    cashbackPercentage: 12,
    minimumSpend: 150,
    cashbackCap: 250,
    startDate: "2025-09-01",
    endDate: "2025-12-31",
    budgetUtilization: "fixed_duration",
    durationDays: 121,
    channel: "online",
    distributionBank: "DIB",
    createdAt: "2025-08-12",
    activatedAt: "2025-09-01",
    completedAt: "2025-12-31",
  },
  {
    id: "camp-faces-winter",
    brandId: "faces",
    name: "Winter Glow Cashback",
    status: "scheduled",
    budget: 25000,
    cashbackPercentage: 8,
    minimumSpend: 100,
    cashbackCap: 150,
    startDate: "2026-11-01",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "in_store",
    distributionBank: "Mashreq",
    createdAt: "2026-08-20",
    activatedAt: null,
    completedAt: null,
  },

  // Tryano
  {
    id: "camp-tryano-eid",
    brandId: "tryano",
    name: "Eid Shopping Rewards",
    status: "completed",
    budget: 40000,
    cashbackPercentage: 17,
    minimumSpend: 300,
    cashbackCap: 500,
    startDate: "2026-01-01",
    endDate: "2026-02-28",
    budgetUtilization: "fixed_duration",
    durationDays: 58,
    channel: "both",
    distributionBank: "Emirates NBD",
    createdAt: "2025-12-08",
    activatedAt: "2026-01-01",
    completedAt: "2026-02-28",
  },
  {
    id: "camp-tryano-thanksgiving",
    brandId: "tryano",
    name: "Thanksgiving Cashback",
    status: "completed",
    budget: 22000,
    cashbackPercentage: 20,
    minimumSpend: 250,
    cashbackCap: 400,
    startDate: "2025-11-20",
    endDate: "2025-12-20",
    budgetUtilization: "fixed_duration",
    durationDays: 30,
    channel: "online",
    distributionBank: "Emirates NBD",
    createdAt: "2025-11-01",
    activatedAt: "2025-11-20",
    completedAt: "2025-12-20",
  },
  {
    id: "camp-tryano-preview",
    brandId: "tryano",
    name: "New Season Preview",
    status: "pending_approval",
    budget: 18000,
    cashbackPercentage: 15,
    minimumSpend: 200,
    cashbackCap: 300,
    startDate: "2026-09-15",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "both",
    distributionBank: "ADCB",
    createdAt: "2026-08-22",
    activatedAt: null,
    completedAt: null,
  },

  // Tanagra
  {
    id: "camp-tanagra-ramadan",
    brandId: "tanagra",
    name: "Ramadan Rewards",
    status: "active",
    budget: 60000,
    cashbackPercentage: 15,
    minimumSpend: 250,
    cashbackCap: 350,
    startDate: "2026-03-01",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "in_store",
    distributionBank: "ADIB",
    createdAt: "2026-02-01",
    activatedAt: "2026-03-01",
    completedAt: null,
  },
  {
    id: "camp-tanagra-backtoschool",
    brandId: "tanagra",
    name: "Back to School",
    status: "scheduled",
    budget: 15000,
    cashbackPercentage: 3,
    minimumSpend: 100,
    cashbackCap: 100,
    startDate: "2026-09-20",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "both",
    distributionBank: "RAKBANK",
    createdAt: "2026-08-05",
    activatedAt: null,
    completedAt: null,
  },
  {
    id: "camp-tanagra-national-day",
    brandId: "tanagra",
    name: "National Day Special",
    status: "completed",
    budget: 20000,
    cashbackPercentage: 9,
    minimumSpend: 150,
    cashbackCap: 200,
    startDate: "2025-11-25",
    endDate: "2025-12-05",
    budgetUtilization: "fixed_duration",
    durationDays: 10,
    channel: "in_store",
    distributionBank: "RAKBANK",
    createdAt: "2025-11-10",
    activatedAt: "2025-11-25",
    completedAt: "2025-12-05",
  },

  // LEVEL Shoes
  {
    id: "camp-level-halloween",
    brandId: "level-shoes",
    name: "Halloween Special",
    status: "pending_approval",
    budget: 28000,
    cashbackPercentage: 8,
    minimumSpend: 200,
    cashbackCap: 250,
    startDate: "2026-10-01",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "both",
    distributionBank: "ADCB",
    createdAt: "2026-08-18",
    activatedAt: null,
    completedAt: null,
  },
  {
    id: "camp-level-spring",
    brandId: "level-shoes",
    name: "Spring Step Up",
    status: "active",
    budget: 35000,
    cashbackPercentage: 11,
    minimumSpend: 200,
    cashbackCap: 300,
    startDate: "2026-04-15",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "online",
    distributionBank: "Mashreq",
    createdAt: "2026-03-20",
    activatedAt: "2026-04-15",
    completedAt: null,
  },
  {
    id: "camp-level-newyear",
    brandId: "level-shoes",
    name: "New Year Refresh",
    status: "completed",
    budget: 24000,
    cashbackPercentage: 14,
    minimumSpend: 150,
    cashbackCap: 250,
    startDate: "2026-01-01",
    endDate: "2026-01-31",
    budgetUtilization: "fixed_duration",
    durationDays: 31,
    channel: "in_store",
    distributionBank: "DIB",
    createdAt: "2025-12-10",
    activatedAt: "2026-01-01",
    completedAt: "2026-01-31",
  },

  // Sephora
  {
    id: "camp-sephora-glow-up",
    brandId: "sephora",
    name: "Glow Up Cashback",
    status: "active",
    budget: 45000,
    cashbackPercentage: 12,
    minimumSpend: 200,
    cashbackCap: 300,
    startDate: "2026-06-01",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "both",
    distributionBank: "ADCB",
    createdAt: "2026-05-05",
    activatedAt: "2026-06-01",
    completedAt: null,
  },
  {
    id: "camp-sephora-fragrance",
    brandId: "sephora",
    name: "Fragrance Week",
    status: "active",
    budget: 20000,
    cashbackPercentage: 9,
    minimumSpend: 150,
    cashbackCap: 200,
    startDate: "2026-08-10",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "in_store",
    distributionBank: "Emirates NBD",
    createdAt: "2026-07-18",
    activatedAt: "2026-08-10",
    completedAt: null,
  },
  {
    id: "camp-sephora-launch",
    brandId: "sephora",
    name: "New Arrivals Launch",
    status: "completed",
    budget: 16000,
    cashbackPercentage: 10,
    minimumSpend: 100,
    cashbackCap: 150,
    startDate: "2026-02-01",
    endDate: "2026-02-28",
    budgetUtilization: "fixed_duration",
    durationDays: 28,
    channel: "online",
    distributionBank: "ADIB",
    createdAt: "2026-01-15",
    activatedAt: "2026-02-01",
    completedAt: "2026-02-28",
  },

  // MAC Cosmetics
  {
    id: "camp-mac-bold",
    brandId: "mac-cosmetics",
    name: "Bold Lips Cashback",
    status: "completed",
    budget: 12000,
    cashbackPercentage: 10,
    minimumSpend: 120,
    cashbackCap: 150,
    startDate: "2026-03-10",
    endDate: "2026-04-10",
    budgetUtilization: "fixed_duration",
    durationDays: 31,
    channel: "in_store",
    distributionBank: "Mashreq",
    createdAt: "2026-02-20",
    activatedAt: "2026-03-10",
    completedAt: "2026-04-10",
  },
  {
    id: "camp-mac-holiday",
    brandId: "mac-cosmetics",
    name: "Holiday Glam",
    status: "scheduled",
    budget: 18000,
    cashbackPercentage: 13,
    minimumSpend: 150,
    cashbackCap: 250,
    startDate: "2026-12-01",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "both",
    distributionBank: "DIB",
    createdAt: "2026-08-25",
    activatedAt: null,
    completedAt: null,
  },
  {
    id: "camp-mac-preview",
    brandId: "mac-cosmetics",
    name: "Collector's Edition Preview",
    status: "rejected",
    budget: 10000,
    cashbackPercentage: 25,
    minimumSpend: 100,
    cashbackCap: 400,
    startDate: "2026-09-01",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "online",
    distributionBank: "ADCB",
    createdAt: "2026-08-14",
    activatedAt: null,
    completedAt: null,
  },

  // The Body Shop
  {
    id: "camp-bodyshop-earth",
    brandId: "body-shop",
    name: "Earth Day Cashback",
    status: "active",
    budget: 14000,
    cashbackPercentage: 10,
    minimumSpend: 100,
    cashbackCap: 150,
    startDate: "2026-04-20",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "both",
    distributionBank: "RAKBANK",
    createdAt: "2026-03-28",
    activatedAt: "2026-04-20",
    completedAt: null,
  },
  {
    id: "camp-bodyshop-selfcare",
    brandId: "body-shop",
    name: "Self-Care Sunday",
    status: "completed",
    budget: 9000,
    cashbackPercentage: 8,
    minimumSpend: 80,
    cashbackCap: 100,
    startDate: "2026-05-01",
    endDate: "2026-05-31",
    budgetUtilization: "fixed_duration",
    durationDays: 30,
    channel: "in_store",
    distributionBank: "Mashreq",
    createdAt: "2026-04-10",
    activatedAt: "2026-05-01",
    completedAt: "2026-05-31",
  },
  {
    id: "camp-bodyshop-festive",
    brandId: "body-shop",
    name: "Festive Gift Sets",
    status: "scheduled",
    budget: 17000,
    cashbackPercentage: 12,
    minimumSpend: 120,
    cashbackCap: 200,
    startDate: "2026-11-15",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "online",
    distributionBank: "ADIB",
    createdAt: "2026-08-28",
    activatedAt: null,
    completedAt: null,
  },

  // Bath & Body Works
  {
    id: "camp-bbw-signature",
    brandId: "bath-body-works",
    name: "Signature Scent Cashback",
    status: "active",
    budget: 26000,
    cashbackPercentage: 10,
    minimumSpend: 100,
    cashbackCap: 150,
    startDate: "2026-05-15",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "both",
    distributionBank: "ADCB",
    createdAt: "2026-04-22",
    activatedAt: "2026-05-15",
    completedAt: null,
  },
  {
    id: "camp-bbw-summer-mist",
    brandId: "bath-body-works",
    name: "Summer Mist Days",
    status: "completed",
    budget: 11000,
    cashbackPercentage: 7,
    minimumSpend: 80,
    cashbackCap: 100,
    startDate: "2026-06-15",
    endDate: "2026-07-15",
    budgetUtilization: "fixed_duration",
    durationDays: 30,
    channel: "in_store",
    distributionBank: "Emirates NBD",
    createdAt: "2026-05-25",
    activatedAt: "2026-06-15",
    completedAt: "2026-07-15",
  },
  {
    id: "camp-bbw-candle-days",
    brandId: "bath-body-works",
    name: "Candle Days",
    status: "pending_approval",
    budget: 15000,
    cashbackPercentage: 9,
    minimumSpend: 100,
    cashbackCap: 150,
    startDate: "2026-10-10",
    endDate: null,
    budgetUtilization: "exhaust",
    durationDays: null,
    channel: "online",
    distributionBank: "DIB",
    createdAt: "2026-08-19",
    activatedAt: null,
    completedAt: null,
  },
]

export function brandById(id: string) {
  return BRANDS.find((b) => b.id === id)
}

export function campaignById(id: string) {
  return CAMPAIGNS.find((c) => c.id === id)
}

export function campaignsForBrand(brandId: string) {
  return CAMPAIGNS.filter((c) => c.brandId === brandId)
}
